// AUTO-GENERATED by scripts/scan-fonts.mjs — 편집하지 마세요.
// public/fonts/ 의 폰트 파일을 스캔해 생성됩니다. `pnpm fonts:scan` 또는 build(prebuild) 시 갱신.
import type { CustomFont } from "@/lib/customFonts";

export const LOCAL_FONTS: CustomFont[] = [];
