// public/fonts/ 의 폰트 파일을 스캔해 src/config/localFonts.generated.ts 를 생성한다.
// serverless 런타임은 레포 파일시스템을 읽을 수 없으므로, 빌드타임에 매니페스트로 굳혀 둔다.
// 사용: `pnpm fonts:scan` (수동) 또는 build 전 자동(prebuild).
import { readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, extname, basename } from "node:path";

const FONT_DIR = join(process.cwd(), "public", "fonts");
const OUT = join(process.cwd(), "src", "config", "localFonts.generated.ts");

/** 확장자 → @font-face format() */
const FORMATS = {
  ".woff2": "woff2",
  ".woff": "woff",
  ".ttf": "truetype",
  ".otf": "opentype",
};

/** 파일명 → 표시용 폰트 이름 (예: "partial-sans_KR.woff2" → "partial sans KR") */
function prettyName(file) {
  return basename(file, extname(file))
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

if (!existsSync(FONT_DIR)) mkdirSync(FONT_DIR, { recursive: true });

const fonts = readdirSync(FONT_DIR)
  .filter((f) => extname(f).toLowerCase() in FORMATS)
  .sort()
  .map((f) => ({
    name: prettyName(f),
    url: `/fonts/${f}`,
    format: FORMATS[extname(f).toLowerCase()],
  }));

const body = `// AUTO-GENERATED by scripts/scan-fonts.mjs — 편집하지 마세요.
// public/fonts/ 의 폰트 파일을 스캔해 생성됩니다. \`pnpm fonts:scan\` 또는 build(prebuild) 시 갱신.
import type { CustomFont } from "@/lib/customFonts";

export const LOCAL_FONTS: CustomFont[] = ${JSON.stringify(fonts, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`[scan-fonts] ${fonts.length} local font(s) detected → ${OUT}`);
